services:
  cli:
    build:
      context: ./cli_project
    networks:
      - dogs-net
    container_name: dogs-cli
    volumes:
      - ./data/results:/usr/src/ml_project/data/results

  ml:
    build:
      context: ./ml_project
    networks:
      - dogs-net
    container_name: dogs-ml
    environment:
      - SCRAPER_API_KEY=e8f1c1b9654655a2d6ebd2e28bd2b39c
    volumes:
      - ./data/results:/usr/src/ml_project/data/results

networks:
  dogs-net:
    driver: bridge