import scrapy

class DogItem(scrapy.Item):
    name = scrapy.Field()
    forecast = scrapy.Field()
    comments = scrapy.Field()
    trackName = scrapy.Field()
    raceClass = scrapy.Field()
    race_date_time = scrapy.Field()
    trapNumber = scrapy.Field()
    raceDistance = scrapy.Field()

    by_1 = scrapy.Field()
    run_time_1 = scrapy.Field()
    comnt_1 = scrapy.Field()
    dist_1 = scrapy.Field()
    going_1 = scrapy.Field()
    race_grade_1 = scrapy.Field()
    odds_1 = scrapy.Field()
    finished_1 = scrapy.Field()
    sec_time_1 = scrapy.Field()
    trap_1 = scrapy.Field()
    weight_1 = scrapy.Field()

    by_2 = scrapy.Field()
    run_time_2 = scrapy.Field()
    comnt_2 = scrapy.Field()
    dist_2 = scrapy.Field()
    going_2 = scrapy.Field()
    race_grade_2 = scrapy.Field()
    odds_2 = scrapy.Field()
    finished_2 = scrapy.Field()
    sec_time_2 = scrapy.Field()
    trap_2 = scrapy.Field()
    weight_2 = scrapy.Field()

    by_3 = scrapy.Field()
    run_time_3 = scrapy.Field()
    comnt_3 = scrapy.Field()
    dist_3 = scrapy.Field()
    going_3 = scrapy.Field()
    race_grade_3 = scrapy.Field()
    odds_3 = scrapy.Field()
    finished_3 = scrapy.Field()
    sec_time_3 = scrapy.Field()
    trap_3 = scrapy.Field()
    weight_3 = scrapy.Field()

    by_4 = scrapy.Field()
    run_time_4 = scrapy.Field()
    comnt_4 = scrapy.Field()
    dist_4 = scrapy.Field()
    going_4 = scrapy.Field()
    race_grade_4 = scrapy.Field()
    odds_4 = scrapy.Field()
    finished_4 = scrapy.Field()
    sec_time_4 = scrapy.Field()
    trap_4 = scrapy.Field()
    weight_4 = scrapy.Field()

    by_5 = scrapy.Field()
    run_time_5 = scrapy.Field()
    comnt_5 = scrapy.Field()
    dist_5 = scrapy.Field()
    going_5 = scrapy.Field()
    race_grade_5 = scrapy.Field()
    odds_5 = scrapy.Field()
    finished_5 = scrapy.Field()
    sec_time_5 = scrapy.Field()
    trap_5 = scrapy.Field()
    weight_5 = scrapy.Field()